login/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shia_app.urls')),
]

shia_app/urls.py
from django.urls import path
from shia_app import views
from django.conf import settings
from django.conf.urls.static import static
app_name='shia_app'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('signin/', views.signin, name='signin'),
    path('admin_panel/', views.admin_panel, name='admin_panel'),
    path('project_list', views.project_list, name='project_list'),
    path('delete/<int:project_id>/', views.delete_project, name='delete_project'),
    path('update/<int:id>/',views.update_project,name='update_project'),
    path('dashboard/',views.dashboard,name='dashboard'),
    path('logout/', views.logout_view, name='logout'),
    path('upload/',views.upload,name='upload'),
    path('email/',views.email,name='email'),
    path('bulk_email/', views.bulk_email, name='bulk_email'),
    path('project_status/',views.status,name='status'),
    path('edit/', views.edit_status, name='edit_status'),
    path('edit_project/', views.edit_project, name='edit_project'),
    path('update_edit/',views.update_edit,name='update_edit'),
      path('profile/', views.profile, name='profile'),
      path('profile_update',views.profile_update,name='profile_update'),
     path('delete_edit/<int:id>/', views.delete_edit, name='delete_edit'),
     
    path('projectdetails_edit', views.update_project_detail, name='update_project_detail'),
    path('project_detail', views.project_detail, name='project_detail'),
    path('project',views.project,name='project'),
    path('skill_management/',views.skill_management,name='skill_management'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/admin_panel.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <title>Admin Panel</title>
  <style>
*
{
    margin: 0;
    padding: 0px;
    box-sizing: border-box;
    font-family: sans-serif;
}
body
{
    height: 100vh;
    background-size: cover;
    background-position: center;
}
li
{
    list-style: none;
}
li a {
    text-decoration: none;
    color: #fff;
    font-size:22px;
    font-weight: normal;
}

li a:hover {
    text-decoration: none;
    color: rgb(111, 116, 100);
}header
{
    height: 100px;
    position: relative;
    padding: .05px 2rem;
    background-color: black;
}
.navbar {
    width: 100%;
    height: 60%;
    max-width: 1200px;
    margin: 0 auto;
    display: flex;
    align-items: center; 
    justify-content: space-between;
    padding-left:20px;
    
}
.navbar .logo {
    padding: 30px ;
    color: #fff;
    font-size: 1.5rem;
    font-weight: bold;
}
.navbar .toggle_btn {
    color: #fff;
    font-size: 30px;
    cursor: pointer;
    text-align: left;
    display: none;
    margin-right: auto; 
}
.navbar .links
{
    display: flex;
    
    gap: 30px;
}
.action_btn:active
{
    scale: 0.95;
}
.dropdown_menu {
    display: none;
    position: absolute;
    height: 0;
    right: auto; 
    left: 0; 
    top: 90px;
    width: 300px;
    background: rgb(255, 255, 255,0.1);
    backdrop-filter: blur(15px);
    border-radius: 10px;
    overflow: hidden;
    transition: height .2s cubic-bezier(0.175, 0.885, 0.32, 1.275);
}

  
.dropdown_menu.open 
{
    height: 120px;
}
.dropdown_menu li
{
    padding: 0.7rem;
    display: flex;
    align-items: center;
    justify-content: center;
}
.dropdown_menu li a:hover
{
    
    color:rgb(238, 247, 213) ;

}
.dropdown_menu .action_btn
{
    width: 100%;
    display: flex;
    justify-content: center;
}
@media(max-width: 992px)
{
    .navbar .links,
    .navbar .action_btn
    {
        display: none;
    }
    .navbar .toggle_btn
    {
        display: block;
        position: absolute;
        top: 30px;
        left: 8px;
    }
    .dropdown_menu
    {
        background: rgba(141, 142, 143, 0.822);
        display: block;
        
    }
    .dropdown_menu i{
        margin-top: 0;
        font-size: 30px;
        margin-right:200px;
        color:#fff;
    }
}
@media(max-width: 576px)
{
    .dropdown_menu
    {

        left: 1px;
        width: unset;
    }
}

  </style>
</head>
<body>
  <header>
    <div class="navbar">
        <div class="logo"><h3>Admin Panel</h3></div>
        <div class="toggle_btn">
            <i class="fa-solid fa-bars"></i>
        </div>
        <ul class="links">
            <li>
              <a href="/admin_panel">  <button type="button" class="btn btn-success action_btn">User Credential</button></a>
            </li>
            <li>
                <a href="/project_list">Project Details</a>
            </li>
        </ul>
        
        <a  href="{% url 'shia_app:logout' %}"  class="fas fa-sign-out-alt" 
        style="
        position: absolute;
        color: #fff;
        font-size: 35px;
        right: -50px;
        top: 30px;
        text-decoration: none;"></a>
    </div>
    <div class="dropdown_menu">
        <ul>
            <li><button type="button" class="btn btn-success action_btn">User Credential</button></li>
            <li><a href="#">Project Details</a></li>
        </ul>
        <i class="fa-solid fa-right-from-bracket"></i>
        

    </div>
</header>

<script>
    const toggleBtn = document.querySelector('.toggle_btn')
    const toggleBtnIcon = document.querySelector('.toggle_btn i')
    const dropDownMenu = document.querySelector('.dropdown_menu')
    toggleBtn.onclick = function()
    {
        dropDownMenu.classList.toggle('open')
        const isOpen = dropDownMenu.classList.contains('open')
        toggleBtnIcon.classList = isOpen
        ? 'fa-solid fa-xmark'
        : 'fa-solid fa-bars';
    }
</script>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <h2 style="text-align: center; padding: 20px;">Admin Panel</h2>
  <div class="container">
    <table class="table table-bordered table-striped table-hover text-center">
      <thead class="thead-dark">
        <tr>
          <th>S.No</th>
          <th>User Name</th>
          <th>Status</th>
        
          
        </tr>
      </thead>
      <tbody>
        
        {% for user in users %}
                <tr>
                  <td>{{ forloop.counter }}</td>
                  <td>{{ user.username }}</td>  
                  <td>
                    
                      {% if user.status %}
                        <span class="badge badge-success">Super User</span>
                        <form action="{% url 'shia_app:admin_panel' %}" method="POST" style="display: inline;">
                          {% csrf_token %}
                          <input type="hidden" name="username" value="{{ user.username }}">
                          <input type="hidden" name="action" value="depromote">
                          <button type="submit" class="btn btn-warning">Depromote</button>
                        </form>
                      {% else %}
                        <span class="badge badge-secondary">Not SuperUser</span>
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        <form action="{% url 'shia_app:admin_panel' %}" method="POST" style="display: inline;">
                          {% csrf_token %}
                          <input type="hidden" name="username" value="{{ user.username }}">
                          <input type="hidden" name="action" value="make_admin">
                          <button type="submit" class="btn btn-success">Make SuperUser</button>
                        </form>
                      {% endif %}
                    
                  </td> 
                </tr>
                {% endfor %}
      </tbody>
    </table>
  </div>
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

  
</body>
</html>

templates/content.html
{%load static%}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Project Details</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{% static 'css/content.css' %}">
</head>
<body>
    <div class="header">
        <a href="admin_panel.html">
            <i class="fa fa-arrow-circle-left" aria-hidden="true"></i>Back
        </a>
        <img src="{% static 'images/shia.jpg' %}">
        <p>Shia Sys Tech</p>
    </div>
   
    <div class="heading">
        
        <h2>{{p.projectname}}</h2>
        <div class="line"></div>
        <div class="heading-content">
            <p>
                {{p.log}}
            </p>
        </div>
       
    </div>
</body>
</html>

templates/project edit.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <title>Project Edit</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  <link rel="stylesheet" href="{% static 'css/project edit.css' %}">
</head>
<body>
  <div class="header">
    <a href="/dashboard">
      <i class="fa fa-arrow-circle-left" aria-hidden="true"></i>Back
    </a>
    <img src="{% static 'images/shia.jpg' %}">
    <p>Shia Sys Tech</p>
  </div>

  <i class="fa fa-user-plus" style="font-size: 24px; cursor: pointer;" id="addIcon"></i>

  <div class="container" style="margin-top: 70px;">
    <table class="table table-bordered table-striped table-hover text-center">
      <thead class="thead-dark">
        <tr>
          <th>S.No</th>
          <th>Resource Name</th>
          <th>Task</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        {% for edit in projects %}
        <tr id="row{{ forloop.counter }}">
          <td>{{ forloop.counter }}</td>
          <td>{{ edit.resource_name }}</td>
          <td>{{ edit.task }}</td>
          <td>
          <button type="submit" class="btn btn-primary btn-success" style="background-color: green;" onclick="editRow('{{ forloop.counter }}', '{{ edit.id }}')">Edit</button>
            <a class="btn btn-danger" href="{% url 'shia_app:delete_edit' edit.id %}">Delete</a>

          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  <div class="modal fade" id="editModal" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-body">
          <h4 style="text-align: center;">Edit Project</h4>
          <form id="editForm" method="POST"  action="{% url 'shia_app:update_edit'%}">
            {% csrf_token %}
            <input type="hidden" id="editRowId" name="project_id">
            <p>Resource Name</p>
            <input type="text" id="editResourceName" name="resource_name" placeholder="" required>
            <p>Task</p>
            <input type="text" id="editTask" name="task" placeholder="" required>
            <div style="text-align: center; margin-top: 20px;">
              <button type="submit" class="btn btn-primary btn-success" style="background-color: green;" onclick="updateRow()" >Update</button>
              <button type="button" class="btn btn-danger" data-dismiss="modal">Cancel</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
  <div class="modal fade" id="addModal" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-body">
          <h4 style="text-align: center;">Add Project</h4>
          <form id="addForm" method="POST">
            {% csrf_token %}
            <p>Resource Name</p>
            <input type="text" name="resource_name" id="addResourceName" placeholder="" required>
            <p>Task</p>
            <input type="text" id="addTask" name="task" placeholder="" required>
            <div style="text-align: center; margin-top: 20px;">
              <button type="submit" class="btn btn-primary btn-success" style="background-color: green;" >Add</button>
              <button type="button" class="btn btn-danger" data-dismiss="modal">Cancel</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
  <div class="backdrop"></div>
</body>
<script>
  var editRowId;
  function editRow(rowId,idk) {
    editRowId = rowId;
    var row = document.getElementById("row" + rowId);
    var cells = row.getElementsByTagName("td");
    document.getElementById("editRowId").value = idk;
    console.log("id varala"+idk)
    document.getElementById("editResourceName").value = cells[1].textContent;
    document.getElementById("editTask").value = cells[2].textContent;
    $('#editModal').modal('show');
  }

  function updateRow() {
    if (editRowId) {
      var resourceName = document.getElementById("editResourceName").value;
      var task = document.getElementById("editTask").value;
      var row = document.getElementById("row" + editRowId);
      var cells = row.getElementsByTagName("td");
      cells[1].textContent = resourceName;
      cells[2].textContent = task;
      $('#editModal').modal('hide');
      editRowId = null;
    }
  }
  function openAddModal() {
    $('#addModal').modal('show');
  }

  function addRow() {
    var resourceName = document.getElementById("addResourceName").value;
    var task = document.getElementById("addTask").value;
    var newRowId = "row" + (document.getElementsByTagName("tr").length + 1);
    var newRow = document.createElement("tr");
    newRow.id = newRowId;
    newRow.innerHTML = "<td>" + (document.getElementsByTagName("tr").length) + "</td>" +
      "<td>" + resourceName + "</td>" +
      "<td>" + task + "</td>" +
      "<td>" +
      "<button type='button' class='btn btn-success' onclick='editRow(\"" + newRowId + "\")'>Edit</button>&nbsp;" +
      "<button type='button' class='btn btn-danger' onclick='deleteRow(\"" + newRowId + "\")'>Delete</button>" +
      "</td>";

    document.querySelector("tbody").appendChild(newRow);
    document.getElementById("addResourceName").value = "";
    document.getElementById("addTask").value = "";
    $('#addModal').modal('hide');
  }
  document.getElementById("addIcon").addEventListener("click", openAddModal);
</script>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</html>

templates/project list.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  <link rel="stylesheet" href="{% static 'css/project list design.css' %}">
    
  <title>Project List</title>
  <style>
    *
{
    margin: 0;
    padding: 0px;
    box-sizing: border-box;
    font-family: sans-serif;
}
body
{
    height: 100vh;
    background-size: cover;
    background-position: center;
}
li
{
    list-style: none;
}
li a {
    text-decoration: none;
    color: #fff;
    font-size:22px;
    font-weight: normal;
}

li a:hover {
    text-decoration: none;
    color: rgb(111, 116, 100);
}header
{
    height: 100px;
    position: relative;
    padding: .05px 2rem;
    background-color: black;
}
.navbar {
    width: 100%;
    height: 60%;
    max-width: 1200px;
    margin: 0 auto;
    display: flex;
    align-items: center; 
    justify-content: space-between;
    padding-left:20px;
    
}
.navbar .logo {
    padding: 30px ;
    color: #fff;
    font-size: 1.5rem;
    font-weight: bold;
}
.navbar .toggle_btn {
    color: #fff;
    font-size: 30px;
    cursor: pointer;
    text-align: left;
    display: none;
    margin-right: auto; 
}
.navbar .links
{
    display: flex;
    
    gap: 30px;
}
.action_btn:active
{
    scale: 0.95;
}
.dropdown_menu {
    display: none;
    position: absolute;
    height: 0;
    right: auto; 
    left: 0; 
    top: 90px;
    width: 300px;
    background: rgb(255, 255, 255,0.1);
    backdrop-filter: blur(15px);
    border-radius: 10px;
    overflow: hidden;
    transition: height .2s cubic-bezier(0.175, 0.885, 0.32, 1.275);
}

  
.dropdown_menu.open 
{
    height: 120px;
}
.dropdown_menu li
{
    padding: 0.7rem;
    display: flex;
    align-items: center;
    justify-content: center;
}
.dropdown_menu li a:hover
{
    
    color:rgb(238, 247, 213) ;

}
.dropdown_menu .action_btn
{
    width: 100%;
    display: flex;
    justify-content: center;
}
@media(max-width: 992px)
{
    .navbar .links,
    .navbar .action_btn
    {
        display: none;
    }
    .navbar .toggle_btn
    {
        display: block;
        position: absolute;
        top: 30px;
        left: 8px;
    }
    .dropdown_menu
    {
        background: rgba(141, 142, 143, 0.822);
        display: block;
        
    }
}
@media(max-width: 576px)
{
    .dropdown_menu
    {

        left: 1px;
        width: unset;
    }
}
  </style>
</head>
 
<body>
  <header>
    <div class="navbar">
        <div class="logo"><h3>Admin Panel</h3></div>
        <div class="toggle_btn">
            <i class="fa-solid fa-bars"></i>
        </div>
        <ul class="links">
            <li>
                <a href="/admin_panel">User Credential</a>
                
            </li>
            <li>
               <a href="/project_list"> <button type="button" class="btn btn-success action_btn">Project Details</button></a>
            </li>
        </ul>
    </div>
    <div class="dropdown_menu">
        <ul>
            <li><a href="#">User Credential</a></li>
            <li><button type="button" class="btn btn-success action_btn">Project Details</button></li>
        </ul>
    </div>
</header>

<script>
    const toggleBtn = document.querySelector('.toggle_btn')
    const toggleBtnIcon = document.querySelector('.toggle_btn i')
    const dropDownMenu = document.querySelector('.dropdown_menu')
    toggleBtn.onclick = function()
    {
        dropDownMenu.classList.toggle('open')
        const isOpen = dropDownMenu.classList.contains('open')
        toggleBtnIcon.classList = isOpen
        ? 'fa-solid fa-xmark'
        : 'fa-solid fa-bars';
    }
</script>


<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  <h2 style="text-align: center; padding: 20px;">Project List</h2>
  <i class="fa-sharp fa-solid fa-user-plus"></i>
    
  <div class="container">
    <table class="table table-bordered table-striped table-hover text-center">
      <thead class="thead-dark">
        <tr>
          <th>S.No</th>
          <th>Project Name</th>
          <th>Manager</th>
          <th>Resources</th>
          <th>Gender</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        
        {% for project in projects %}
        <tr>
          <td>{{ forloop.counter }}</td>
          <td>{{ project.project_name }}</td>
          <td>{{ project.manager }}</td>
          <td>{{ project.resources }}</td>
          <td>{{ project.male_count }}M, {{ project.female_count }}F</td>
          <td>
          <a class="btn btn-primary btn-success" href="{% url 'shia_app:update_project' project.id %}"> Edit </a>      
          <a class="btn btn-danger" href="{% url 'shia_app:delete_project' project.id %}">Delete</a>
          </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
  </div>
  
  <div class="modal fade" id="myModal">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-body">
          <h4 style="text-align: center;">Project List</h4>
          <form id="myForm" method="POST">
            {% csrf_token %}
            <p>Project Name</p>
            <input type="text" id="projectName" placeholder="" name="project_name" required>
            <p>Manager</p>
            <select id="manager" name="manager" required>
              <option value="" selected disabled>Select</option>
              <option value="Amal" name="Amal">Amal</option>
              <option value="Aravind" name="Aravind">Aravind</option>
              <option value="Siva Sankar" name="sivasankar">Siva Sankar</option>
              <option value="Gokul" name="Gokul">Gokul</option>
            </select>
            <p>Resources</p>
            <input type="number" id="resources" name="resources" placeholder="" required>
            <p>Gender</p>
            <div class="gender" >
              <p>Male</p>
              <input type="number" name="maleCount" id="maleCount" placeholder="" required>
              <p>Female</p>
              <input type="number" name="femaleCount" id="femaleCount" placeholder="" required>
            </div>
            <div style="text-align: center; margin-top: 20px;">
              <button type="button" class="btn btn-primary btn-success" style="background-color: green;" onclick="validateForm()">Submit</button>
              <a href="/project_list"><button type="button" class="btn btn-danger">Cancel</button></a>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
  
  <script>
    function validateForm() {
      var projectName = document.getElementById("projectName").value;
      var manager = document.getElementById("manager").value;
      var resources = document.getElementById("resources").value;
      var maleCount = document.getElementById("maleCount").value;
      var femaleCount = document.getElementById("femaleCount").value;
  
      if (projectName === "" || manager === "" || resources === "" || maleCount === "" || femaleCount === "") {
        alert("Please fill the details in all fields.");
        return;
      }
  
      document.getElementById("myForm").submit();
    }
  </script>
   <div class="backdrop"></div>
  
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  
  <script>
    $(document).ready(function() {
      $('i.fa-user-plus').click(function() {
        $('#myModal').modal({
          backdrop: 'static', 
          keyboard: false     
        });
      });
      $('.backdrop').click(function(event) {
                if (event.target === this) {
        }
      });
    });
  </script>
  
</body>
</html>

templates/project status.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Status</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
          integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA=="
          crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{% static 'css/project status.css' %}">
</head>
<body>
<div class="header">
    <img src="{% static 'images/shia.jpg' %}">
    <p>Shia Sys Tech</p>
    <a href="/dashboard">
        <i class="fa fa-arrow-circle-left" aria-hidden="true"></i>Back
    </a>
</div>
<div class="content">
    <h2>Project</h2><br>
    <p>Saas Management System</p>
    <img src="{% static 'images/User.png' %}">
    <a href="#">user@gmail.com</a>
</div>
<div class="line"></div>
<div class="datas">
    <table>
        <thead>
        <tr>
            <th>S.No</th>
            <th>Status</th>
            <th>Progress</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
        {% for status_var in projects %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ status_var.Status }}</td>
            <td>{{ status_var.Progress }}</td>
            <td>
                <a class="btn btn-primary btn-success" onclick="showEditForm('{{forloop.counter}}','{{ status_var.Status }}', '{{ status_var.Progress }}')">Edit</a>
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
<div class="modal" id="editModal" tabindex="-1" role="dialog" style="display: none;">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Edit Status and Progress</h5>
            </div>
            <form id="myForm" method="POST" action="{% url 'shia_app:edit_status' %}">
                {% csrf_token %}
                <div class="modal-body">
                    
                    <p>Progress</p>
                    <input type="hidden" id="ID" name="id" >
                    <input type="text" id="progressInput" name="progress" placeholder="" required>
                    <p>Status</p>
                    <input type="text" id="statusInput" name="status" placeholder="" required>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary btn-success" style="background-color: green;" >Submit</button>
                    <button type="button" class="btn btn-danger" onclick="hideEditForm()">Cancel</button>
                </div>
            </form>
        </div>
    </div>
</div>
<div class="backdrop" style="display: none;"></div>
<script>
    function showEditForm(id,status, progress) {
        document.getElementById("ID").value=id;
        document.getElementById("statusInput").value = status;
        document.getElementById("progressInput").value = progress;
        document.getElementById("editModal").style.display = "block";
        document.querySelector(".backdrop").style.display = "block";
    }

    function hideEditForm() {
        document.getElementById("editModal").style.display = "none";
        document.querySelector(".backdrop").style.display = "none";
    }

    function validateForm() {
        var progress = document.getElementById("progressInput").value;
        var status = document.getElementById("statusInput").value;

        if (progress === "" || status === "") {
            alert("Please fill in all fields.");
            return false;
        }

        hideEditForm();
        return true;
    }
</script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

templates/project_count.html
<!DOCTYPE html>
<html>
<head>
    <title>Project Count</title>
</head>
<body>
    <center><h1>Total Users: {{ project_count }}</h1></center>
</body>
</html>